@echo off
echo Zipping Lambda code...
powershell Compress-Archive -Path sentiment_handler.py -DestinationPath function.zip -Force
echo Deploying to AWS Lambda...
aws lambda update-function-code --function-name MovieSentimentHandler --zip-file fileb://function.zip --region us-east-1
echo Done!
